include: package:flutter_lints/flutter.yaml

linter:
  rules:

    # UIパフォーマンス
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true

    # コード安全性
    avoid_unnecessary_containers: true
    unnecessary_this: true

    # ZERON用（ログ抑制）
    avoid_print: false