name: zeron
description: ZERON TOKYO mobile decarbonization participation app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.8
  pedometer: ^4.0.1
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/brand/
    - assets/icon/

flutter_icons:
  macos:
    generate: true
    image_path: "assets/icon/zeron_app_icon.png"